name: moogallery
author: abidibo
category: Widgets
tags: [gallery, images, lightbox, audio, video, media]
docs: http://www.abidibo.net/projects/js/moogallery
demo: http://www.abidibo.net/projects/js/moogallery/demo
current: 0.2.3
